In [3]:
import pandas as pd
import json 

d = {1: ['2134',20, 1,1,1,0], 2: ['1010',5, 1,0,0,0], 3: ['3457',15, 0,1,1,0]}
columns=['Code', 'Price', 'Bacon','Onion','Tomato', 'Cheese'] 

df = pd.DataFrame.from_dict(data=d, orient='index').sort_index()
df.columns = columns

df.head()

Code  Price  Bacon  Onion  Tomato  Cheese
1  2134     20      1      1       1       0
2  1010      5      1      0       0       0
3  3457     15      0      1       1       0

In [35]:
a=[10, 20, 30,40,50]
print(a)

# Implement Moving Average. 


movingAverage=[]
for i in range(0, len(a)-1):
    movingAverage.append((a[i]+a[i+1])/2)
    
movingAverage

[10, 20, 30, 40, 50]


[15.0, 25.0, 35.0, 45.0]

In [36]:
# Implement Moving Average using numpy

import numpy as np

a=np.array(a)
print(a)

c= np.roll(a, -1)

print(c)
d=np.sum((a, c), axis=0)/2
movingAverage=d[:-1]

movingAverage

[10 20 30 40 50]
[20 30 40 50 10]


array([15., 25., 35., 45.])